# Combining pre-commit and unit-test into one workflow.

name: CI

on:
  push:

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0

  unit-test:
    runs-on: ubuntu-latest
    needs: pre-commit

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
